# Generated by Django 4.2.6 on 2023-10-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'дочерний элемент',
                'verbose_name_plural': 'дочерние элементы',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='ссылка айтема')),
                ('children', models.ManyToManyField(blank=True, null=True, to='main.childrenelement', verbose_name='дочерние элементы')),
            ],
            options={
                'verbose_name': 'элемент меню',
                'verbose_name_plural': 'элементы меню',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='название меню')),
                ('slug', models.SlugField(default=None, max_length=255, unique=True, verbose_name='ссылка меню')),
                ('items', models.ManyToManyField(to='main.menuitem', verbose_name='айтемы')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'менюшки',
                'ordering': ('title',),
            },
        ),
    ]
